### ISSUE TITLE
Add Https support 

### ISSUE THREAD

**Issue by crazy4pi314** [stephenjordan/stephenjordan.github.io#6]
It seems like right now the Algorithm Zoo is not being hosted over HTTPS, that can cause some security issues and some browsers not even put up warnings. I think all you need to do is enforce https in the GitHub pages settings?

**Comment by marwahaha** [comment]
I think HTTPS is allowed, but not enforced.
https://quantumalgorithmzoo.org/
http://quantumalgorithmzoo.org/

**Comment by stephenjordan** [comment]
Thanks for pointing this out. I have adjusted the settings. So I think it should enforce https now.

**Comment by stephenjordan** [comment]
Seems to be fixed now.
