### ISSUE TITLE
Caltech resource link resolves in 404

### ISSUE THREAD

**Issue by chinchalupa** [stephenjordan/stephenjordan.github.io#7]
The CalTech resource link returns a 404. Link should be updated or removed if content is no longer available. https://github.com/stephenjordan/stephenjordan.github.io/blob/f7fd6e9fda135507790bab2eb96b7a9e6042a14b/index.html#L4779
![image](https://user-images.githubusercontent.com/6162129/95774647-6be12400-0c86-11eb-963e-d2fa352a647a.png)
![image](https://user-images.githubusercontent.com/6162129/95774685-78fe1300-0c86-11eb-85e0-2ecd29aadccd.png)

**Comment by stephenjordan** [comment]
Thanks for pointing this out. I have updated the link.
